language: python
python:
  - "2.7"
env:
  - REPO=lyft/metadataproxy
sudo: required
services:
  - docker
before_install:
  - docker build -f Dockerfile -t $REPO:$TRAVIS_COMMIT .
install: "pip install -r requirements.txt"
script: make test
after_success:
  - ./docker_push.sh
deploy:
  provider: pypi
  user: lyftpypi
  password:
    secure: RigAIMowmRVP7xGdra9mDu9aG2xmImxEQo5zOz1x6EP0xqMuSus+PEVbJAVLxpptElJx2FJpkYa5rNvNnrUuxVLaMxxgZE9bbleP8gKX/+/qt4ua+0pjpRMsvmxFzmJhwepMrWsvIwxQvk3lKlVcahZlXAlauP5lF5ocYtY7TBk4dtFYJdKtcPOwUCPezerQU+FLDom5yHeTT0D5AJb8N/9Z0KYdeJ163viSQxV8Q+VWX9mbUa3hjkHTJyCcRcZeXMAHRqvs2ZrZAK7hQNbJuPNZi4ikqAdABdnmZv/hAqhl4099Tydr+o/cwY/ckQQaOW2a58PXjqfD+eQV1vtbfydreAZowvjzn1Bctmt/Da4NZWZL2Nt/0ckssm+3yxKHb+UkTJyrQfC9QwoO7ChzrFkltvBvssZvBA6cN0mPFAPLtAD81b4BD14bp8+O+dordkHn/1R9Iw8Y5q7M6nEHKLYCCw2YDjmwb4CeOzdGN/8TtdBPBehKCoYIoKcduYMPiNmE6ydaP5e5L8FzRtivS7sI6DZmr+5lknA+rHjoQG8/GjV8SulsM4wwwTBFSTLwpmRmLyzNSq2jVdzksPzcp7PHBir0aWNWKG7TeL2Wzv97y6b1GAYkj+/LeXgrPgHmQQ7k1ph8bHZHSN8CwdnS4IUC5iAvOu27Y69znyObvzo=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: lyft/metadataproxy
